# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lee Jihoon
title: Junior Backend Developer
email: ljh2723@gmail.com
website: https://github.com/jihoonLeee

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  jihoonLeee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: zzzihooon
linkedin_username: 지훈-이-281717213
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: tistory
  icon: fas fa-blog
  url: https://jihoon2723.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title:
about_profile_image: images/resume_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요! 자바와 스프링, Mybatis, MySQL을 주로 이용한 3년차 백엔드 개발자 이지훈입니다.

제가 가장 중요하게 생각하는 것은 '학습'과 '성장'입니다. 그래서 주도적이고 효율적인 학습 환경을 찾아 나아가는 것에 큰 가치를 두고 있습니다. 그 결과로 기술 블로그를 운영하며 사이드 프로젝트를 진행하고 있으며, 이런 과정을 통해 계속해서 역량을 쌓아가는 중입니다.

새로운 기술에 대한 도전은 제 자신을 성장시키는 원동력입니다. 현재 React,Node.js에 대해 배우고 있으며, 이러한 새로운 시도를 통해 지식의 폭을 넓혀나가고 있습니다.

높은 트래픽이 발생하는 시스템 환경과 같은 다양한 도전들이 저에게는 새로운 발전의 기회라 생각합니다. 그런 경험들을 많이 해보지 못했다면, 저와 함께 성장할 수 있는 기회를 주셨으면 좋겠습니다.

함께 일할 수 있는 기회를 주셔서 감사합니다. 제 역량으로 최선의 결과를 만들어내겠습니다! 잘 부탁드립니다.
  <mark>Java</mark> <mark>Spring</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Basic Finance 
        link: kr.basic.finance
        sub_title: Junior Backend Developer
        caption: 2022.02 ~ 
        description: | # this will include new lines to allow paragraphs
          Email 서비스를 운영하고 개선해나가고 있습니다. <br><br>
          기술 스택
            - <mark>Java</mark>,<mark>Spring Boot</mark>,
            - <mark>Jenkins</mark>, <mark>Grafana</mark>
            - <mark>Mybatis</mark>, <mark>MySQL</mark>, <mark>Git</mark>

      - title: Basic Finance
        link: kr.basic.finance
        sub_title: Junior Backend Developer
        caption: 2021.01. ~ 2022.01
        description: | # this will include new lines to allow paragraphs
          
  - title: Experience # Title for the section            
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Coredot LAB
        caption: 2023.06 ~ 2023.10
        sub_title: Developer/Validator
        quote: >
            블록체인 기반 서비스 개발사
        description: | # this will include new lines to allow paragraphs
          - Validator 운영
          - 블록체인 관련 서비스 개발
        
      - title: Basic Research
        caption: 2021.06. ~ 2023.05
        sub_title: Developer
        quote: >
          블록체인 기반의 디지털자산관리 토탈 솔루션
        description: | # this will include new lines to allow paragraphs
          - Crypto자산 예치 및 대출 서비스
          - Crypto자산 지갑 서비스
      - title: 인비즈
        caption: 2021.03. ~ 2021.06
        sub_title: Developer
        quote: >
          의료영상 관련 헬스케어 인공지능 전문회사
        description: | # this will include new lines to allow paragraphs
          - 의료영상시스템(PACS) 관련 개발
      - title: Tmax AI
        caption: 2020.11. ~ 2021.03
        sub_title: Intern
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          굿

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Soccer/Futsal
      - Exercise
      - Trip
      - Cooking
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
